apiVersion: v1
kind: Pod
metadata:
  name: init-container-example
spec:
  containers:
  - name: main-app
    image: nginx:latest
    ports:
    - containerPort: 80
  initContainers:
  - name: init-pass
    image: busybox:latest
    command: ["sh", "-c", "echo 'Init container passed!'"]
  - name: init-fail
    image: busybox:latest
    command: ["sh", "-c", "exit 1"]